!Namelist
###############################################################################
# namelist_perfmetrics_CMIP5.xml
#
# Description
# Namelist for plotting the performance metrics for the CMIP5 models,
# including the "standard" ECVs as in Gleckler et al., plus some additional
# variables (like ozone, sea-ice, aerosol...)
#
# Authors
# Franziska Frank (DLR, Germany)
# Mattia Righi (DLR, Germany)
# Veronika Eyring (DLR, Germany)
#
# Project
# DLR ESMVal
#
# Reference
# Gleckler et al., J. Geophys. Res., 113, D06104, doi: 10.1029/2007JD008972
# (2008)
#
# This namelist is part of the ESMValTool
###############################################################################

  MODELS:
    {% for model in models %}{{ model }}
    {% endfor %}

  PREPROCESS:
    - {id: pp1, select_level: {levels: 85000, scheme: linear}, target_grid: ref_model, regrid_scheme: linear, mask_fillvalues: {threshold_percent: 0.95}, mask_landocean: None, multimodel_mean: False}

  CONFIG:
    var_def_scripts: ./variable_defs
    var_only_case: 0

  DIAGNOSTICS:

    ANNUAL_CYCLE_ta:
      !Diagnostic
      id: ANNUAL_CYCLE_ta
      description: tutorial diagnostic
      variables:
        - {name: {{ variable }}, ref_model: ['ERA-Interim','NCEP'], field: T3M, only: None, preproc_id: pp1}
      scripts:
        # Annual cycle plot
        - {script: perfmetrics_main.ncl,  cfg_file: ./nml/cfg_perfmetrics/CMIP5/cfg_perfmetrics_cycle_monthlyclim_glob.ncl}
      additional_models:
        - {name: ERA-Interim,  project: OBS,  type: reanaly,  version: 1,  start_year: {{ start_year }},  end_year: {{ end_year }},  tier: 3}
        - {name: NCEP,         project: OBS,  type: reanaly,  version: 1,  start_year: {{ start_year }},  end_year: {{ end_year }},  tier: 2}
