version: '3'

services:
    backend:
        build: backend
        #        ports:
        #    - "9001:9000"
        volumes:
            - ./backend/config:/config
            - ./backend/adagucdb:/adaguc/adagucdb
            - ./backend/logs:/var/log/adaguc
            - ./backend/adaguc-datasets:/data/adaguc-datasets
            - "${STATIC_DATA_LOCATION}:/data/adaguc-data"
            - "${STATIC_DATA_LOCATION}:/data/adaguc-autowms"
            - ./backend/adaguc-services-controller-home/:/data/adaguc-services-home/
            - ./backend/security:/security
        environment:
            - "EXTERNALADDRESS=https://${EXTERNAL_HOSTNAME}/backend"
            - "COMPUTE_NODE_1_URL=https://compute:9000"
            #  New application can be created at https://console.developers.google.com/apis/credentials
            - "OAUTHCLIENTSECRET=${OAUTHCLIENTSECRET}"
            - "OAUTHCLIENTID=${OAUTHCLIENTID}"
        depends_on:
            - compute
        restart: unless-stopped
    compute:
        build: compute
        #ports:
        #    - "9000:9000"
        volumes:
            - ./compute/processes:/src/pywps/pywps/processes/
            - ./compute/config:/config
            - /data/adaguc-services-compute-home/:/data/adaguc-services-home/
            - /data/climexp:/data/climexp
            - /data/esmvaltool:/data/esmvaltool
            - /data/esmvaltool_output:/data/esmvaltool_output
            - ./compute/security:/security
        environment:
            - "EXTERNALADDRESS=https://compute:9000"
        restart: unless-stopped
    frontend:
        build: frontend
        environment:
          - "BACKEND=https://${EXTERNAL_HOSTNAME}/backend"
          - "COMPUTE=https://compute:9000"
          - "VIEWER=https://${EXTERNAL_HOSTNAME}/adaguc-viewer"
          - "STATICWMS=https://${EXTERNAL_HOSTNAME}/backend/wms"
          #This is usually part of the backend, but you can optionally also use the live version
          #if you do not have the datasets available locally.
        #ports:
        # - "3000:3000"
        #volumes:
                #- ./letsencrypt/.well-known:/frontend/c3s-magic-frontend/dist/.well-known
        depends_on:
          - adaguc-viewer
          - backend
          - compute
        restart: unless-stopped
    adaguc-viewer:
        image: openearth/adaguc-viewer
        #ports:
        #  - "8080:80"
        environment:
          - "ADAGUCSERVICES_AUTOWMS=https://${EXTERNAL_HOSTNAME}/backend/autowms?"
    copernicus-wps:
        build: copernicus-wps
    nginx:
        build: nginx
        ports:
          - "80:80"
          - "443:443"
        env_file:
          - .env
        volumes:
          - ./letsencrypt:/etc/letsencrypt
          - ./cert:/cert
        depends_on:
          - backend
          - compute
          - frontend
          - adaguc-viewer
        restart: unless-stopped
