version: '2'

services:
    backend:
        build: adaguc-services-controller
        #        ports: 
        #    - "9001:9000"
        volumes:
            - ./adaguc-services-controller/config:/config
            - ./adaguc-services-controller/adagucdb:/adaguc/adagucdb
            - ./adaguc-services-controller/logs:/var/log/adaguc
            - ./adaguc-services-controller/adaguc-datasets:/data/adaguc-datasets
            - "${STATIC_DATA_LOCATION}:/data/adaguc-data"
            - "${STATIC_DATA_LOCATION}:/data/adaguc-autowms"
            - ./adaguc-services-controller/adaguc-services-controller-home/:/data/adaguc-services-home/
            - ./adaguc-services-controller/security:/security
        environment:
            - "EXTERNALADDRESS=https://${EXTERNAL_HOSTNAME}/backend"
            - "COMPUTE_NODE_1_URL=http:/compute:9000"
            #  New application can be created at https://console.developers.google.com/apis/credentials 
            - "OAUTHCLIENTSECRET=${OAUTHCLIENTSECRET}"
            - "OAUTHCLIENTID=${OAUTHCLIENTID}"
        depends_on:
            - compute
    compute:
        build: adaguc-services-compute
        #ports: 
        #    - "9000:9000"
        volumes:
            - ./adaguc-services-compute/processes:/src/pywps/pywps/processes/
            - ./adaguc-services-compute/config:/config
            - /data/adaguc-services-compute-home/:/data/adaguc-services-home/
            - /data/climexp:/data/climexp
            - /data/esmvaltool:/data/esmvaltool
            - /data/esmvaltool_output:/data/esmvaltool_output
            - ./adaguc-services-compute/security:/security
        environment:
            - "EXTERNALADDRESS=http://compute:9000"
    frontend:
        build: frontend
        environment: 
          - "BACKEND=https://${EXTERNAL_HOSTNAME}/backend"
          - "COMPUTE=https://compute:9000"
          - "VIEWER=https://${EXTERNAL_HOSTNAME}/adaguc-viewer"
          - "STATICWMS=https://${EXTERNAL_HOSTNAME}/backend/wms"
          #This is usually part of the backend, but you can optionally also use the live version
          #if you do not have the datasets available locally.
        #ports:
        # - "3000:3000"
        #volumes:
                #- ./letsencrypt/.well-known:/frontend/c3s-magic-frontend/dist/.well-known
        depends_on:
          - adaguc-viewer
          - backend
          - compute
    adaguc-viewer:
        image: openearth/adaguc-viewer
        #ports:
        #  - "8080:80"
        environment:
          - "ADAGUCSERVICES_AUTOWMS=https://${EXTERNAL_HOSTNAME}/backend/autowms?"
    nginx:
        build: nginx
        ports:
          - "80:80"
          - "443:443"
        env_file:
          - .env
        volumes:
          - ./letsencrypt:/etc/letsencrypt
          - ./cert:/cert
        depends_on:
          - backend
          - compute
          - frontend
          - adaguc-viewer

# Add 127.0.1.1       portal.c3s-magic.eu to /etc/hosts    (portal.c3s-magic.eu is configured in console.developers.google.com for OAuth2 callback)
# Do docker-compose build --pull
# Do docker-compose up in working directory and go to localhost:80
# Do docker-compose down to stop all
