version: '3'

services:
    backend:
        build: backend
        #        ports:
        #    - "9001:9000"
        volumes:
            - ./backend/config:/config
            - ./backend/adagucdb:/adaguc/adagucdb
            - /data/adaguc-logs/:/var/log/adaguc
            - ./backend/adaguc-datasets:/data/adaguc-datasets
            - "${STATIC_DATA_LOCATION}:/data/adaguc-data"
            - "${STATIC_DATA_LOCATION}:/data/adaguc-autowms"
            - /data/adaguc-services-controller-home/:/data/adaguc-services-home/
            - ./backend/security:/security
        environment:
            - "EXTERNALADDRESS=https://${EXTERNAL_HOSTNAME}/backend"
            - "EXTERNAL_HOSTNAME=${EXTERNAL_HOSTNAME}"
            - "COMPUTE_NODE_2_URL=https://${EXTERNAL_HOSTNAME}/wps?"
            #  New application can be created at https://console.developers.google.com/apis/credentials
            - "OAUTHCLIENTSECRET=${OAUTHCLIENTSECRET}"
            - "OAUTHCLIENTID=${OAUTHCLIENTID}"
            - "CEDA_OAUTHCLIENTSECRET=${CEDA_OAUTHCLIENTSECRET}"
            - "CEDA_OAUTHCLIENTID=${CEDA_OAUTHCLIENTID}"
        restart: unless-stopped
        links:
            - "nginx:${EXTERNAL_HOSTNAME}"
    climexp_numerical_wps:
        image: c3smagic/climexp_numerical_wps
        hostname: climexp_numerical_wps
        volumes:
            - /data/climexp:/data
        restart: unless-stopped
    frontend:
        build: frontend
        environment:
          - "BACKEND=https://${EXTERNAL_HOSTNAME}/backend"
          - "COMPUTE=https://compute:9000"
          - "VIEWER=https://${EXTERNAL_HOSTNAME}/adaguc-viewer"
          - "STATICWMS=https://${EXTERNAL_HOSTNAME}/backend/wms"
          - "DATAURL=https://${EXTERNAL_HOSTNAME}/data"
          #This is usually part of the backend, but you can optionally also use the live version
          #if you do not have the datasets available locally.
        #ports:
        # - "3000:3000"
        #volumes:
                #- ./letsencrypt/.well-known:/frontend/c3s-magic-frontend/dist/.well-known
        depends_on:
          - adaguc-viewer
          - backend
        restart: unless-stopped
    adaguc-viewer:
        image: openearth/adaguc-viewer
        #ports:
        #  - "8080:80"
        environment:
          - "ADAGUCSERVICES_AUTOWMS=https://${EXTERNAL_HOSTNAME}/backend/autowms?"
        restart: unless-stopped
    wps:
        build: c3s-magic-wps
        #debug wps by exposing this port over http
        #ports:
        #  - "5000:5000"
        environment:
          - "WPS_OUTPUT_URL=https://${EXTERNAL_HOSTNAME}/wps/outputs/"
          - "CMIP_DATA_ROOT=/cmip5"
        volumes:
            - "${ESMVALTOOL_CMIP5}:/cmip5"
            - "${ESMVALTOOL_OBS}:/obs"
        restart: unless-stopped
    esgfsearch:
        build: esgfbrowser
        environment:
          - "searchservice=https://${EXTERNAL_HOSTNAME}/backend/esgfsearch/search?"
          - "catalogbrowserservice=https://${EXTERNAL_HOSTNAME}/backend/esgfsearch/catalog?"
          - "adagucservice=https://${EXTERNAL_HOSTNAME}/backend/adagucserver?"
          - "getvariables=https://${EXTERNAL_HOSTNAME}/backend/esgfsearch/getvariables?"
          - "xml2jsonservice=https://${EXTERNAL_HOSTNAME}/backend/xml2json?"
          - "adagucviewer=https://${EXTERNAL_HOSTNAME}/adaguc-viewer"
        ports:
          - "10080:80"
        restart: unless-stopped
    nginx:
        build: nginx
        ports:
          - "80:80"
          - "443:443"
        env_file:
          - .env
        volumes:
          - ./letsencrypt:/etc/letsencrypt
          - ./cert:/cert
          - ./ca-cert:/ca-cert
          - ./backend/security:/backend-security/
          - ${PUBLIC_DATA}:/publicdata
        restart: unless-stopped
